/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface TypeaheadComponent {}
  interface TypeaheadComponentAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'TypeaheadComponent': Components.TypeaheadComponent;
  }

  interface StencilIntrinsicElements {
    'typeahead-component': Components.TypeaheadComponentAttributes;
  }


  interface HTMLTypeaheadComponentElement extends Components.TypeaheadComponent, HTMLStencilElement {}
  var HTMLTypeaheadComponentElement: {
    prototype: HTMLTypeaheadComponentElement;
    new (): HTMLTypeaheadComponentElement;
  };

  interface HTMLElementTagNameMap {
    'typeahead-component': HTMLTypeaheadComponentElement
  }

  interface ElementTagNameMap {
    'typeahead-component': HTMLTypeaheadComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
